# This Makefile is heavily inspired by the one automatically generated by
# the Kubebuilder CLI: https://github.com/kubernetes-sigs/kubebuilder

all: build

##@ General

# The help target prints out all targets with their descriptions organized
# beneath their categories. The categories are represented by '##@' and the
# target descriptions by '##'. The awk command is responsible for reading the
# entire set of makefiles included in this invocation, looking for lines of the
# file as xyz: ## something, and then pretty-format the target and help. Then,
# if there's a line with ##@ something, that gets pretty-printed as a category.
# More info on the usage of ANSI control characters for terminal formatting:
# https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_parameters
# More info on the awk command:
# http://linuxcommand.org/lc3_adv_awk.php

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)


##@ Development

fmt: ## Format the Go and templ files.
	go fmt ./...

fmt-templ: templ ## Format the templ files.
	$(TEMPL) fmt .

vet: ## Run go vet against code.
	go vet ./...

test: ## Test the Go code.
	go test ./...

generate: templ ## Generate Go files based on .templ files.
	$(TEMPL) generate

generate-watch: templ ## Generate Go files based on .templ files, and watch for changes.
	$(TEMPL) generate --watch

##@ Build

build: build-server build-cli ## Build the binaries for the server and CLI.

build-server: fmt fmt-templ vet generate ## Build the server binary.
	go build -o ./bin/server ./cmd/server/main.go

build-cli: fmt vet generate ## Build the CLI binary.
	go build -o ./bin/totb ./cmd/cli/main.go

run-server: fmt fmt-templ vet generate gow ## Run the server.
	go run ./cmd/server/main.go

watch-server: fmt fmt-templ vet generate gow ## Run the server, and watch for changes.
	$(GOW) run ./cmd/server/main.go

run-cli: fmt vet ## Run the CLI.
	go run ./cmd/cli/main.go


##@ Build Dependencies

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

## Tool binaries
TEMPL ?= $(LOCALBIN)/templ
GOW ?= $(LOCALBIN)/gow

.PHONY: templ
templ: $(TEMPL) ## Download templ locally if necessary.
$(TEMPL): $(LOCALBIN)
	test -s $(LOCALBIN)/templ || GOBIN=$(LOCALBIN) go install github.com/a-h/templ/cmd/templ@latest

.PHONY: gow
gow: $(GOW) ## Download gow locally if necessary.
$(GOW): $(LOCALBIN)
	test -s $(LOCALBIN)/gow || GOBIN=$(LOCALBIN) go install github.com/mitranim/gow@latest
